FROM jenkins/jenkins:lts

USER root

COPY deployment/bdastackoverflow-gcp-sa-key.json ./

## Install Docker
#RUN apt-get update && \
#    apt-get -qy full-upgrade && \
#    apt-get install -qy curl && \
#    curl -sSL https://get.docker.com/ | sh

# Install gcloud
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip && \
    apt-get -y install git && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-cli -
    
RUN apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin

# Define environment variables
ENV GOOGLE_APPLICATION_CREDENTIALS=./bdastackoverflow-gcp-sa-key.json

USER jenkins
