FROM python:3.9-slim

RUN apt-get update && apt-get install -y wget

RUN mkdir /bda-stackoverflow-tags
WORKDIR /bda-stackoverflow-tags

COPY requirements.txt .
COPY deployment/bdastackoverflow-gcp-sa-key.json .

ENV GOOGLE_APPLICATION_CREDENTIALS="/bda-stackoverflow-tags/bdastackoverflow-gcp-sa-key.json"

RUN pip install -r requirements.txt

RUN python -m nltk.downloader punkt -d /bda-stackoverflow-tags
RUN python -m nltk.downloader wordnet -d /bda-stackoverflow-tags
RUN python -m nltk.downloader stopwords -d /bda-stackoverflow-tags
RUN python -m nltk.downloader omw-1.4 -d /bda-stackoverflow-tags

