apiVersion: batch/v1
kind: Job
metadata:
  name: bdaproject-stage2-job
spec:
  template:
    spec:
      containers:
      - name: bdaproject-stage2
        image: adarshzededa/bdaproject-stage2:latest
        imagePullPolicy: Always
        command: ["python", "train-the-model.py"]
      restartPolicy: Never
  backoffLimit: 0
