FROM python:3.9-slim

RUN apt-get update && apt-get install -y wget
#RUN wget https://dl.google.com/cloudagents/add-dataproc-agent-repo.sh
#RUN bash add-dataproc-agent-repo.sh
#RUN apt-get update && apt-get install -y google-cloud-sdk google-cloud-sdk-dataproc

RUN mkdir /bda-stackoverflow-tags
WORKDIR /bda-stackoverflow-tags

COPY requirements.txt .
COPY pyspark-job.py .

COPY submit-pyskark-job.py .
COPY bdastackoverflow-5b1b7bc5f4e4.json .

ARG project_id
ARG region
ARG cluster_name
ARG gcs_bucket

ENV MY_CLUSTER='bda-dataproc'
ENV GOOGLE_APPLICATION_CREDENTIALS="/bda-stackoverflow-tags/bdastackoverflow-5b1b7bc5f4e4.json"

RUN pip install -r requirements.txt

CMD ["python", "submit-pyskark-job.py", "--project_id", "$project_id", "--region", "$region", "--cluster_name", "$cluster_name", "--pyspark_file", "/bda-stackoverflow-tags/pyspark-job.py", "--gcs_bucket", "$gcs_bucket"]
